export const releaseFiles = [
  'manifest.json',
  'reader.html',
  'assets/icon-16.png',
  'assets/icon-32.png',
  'assets/icon-48.png',
  'assets/icon-128.png',
  'styles',
  'src',
  'node_modules/foliate-js',
  'node_modules/pdfjs-dist/build',
  'node_modules/pdfjs-dist/cmaps',
  'node_modules/pdfjs-dist/standard_fonts',
  'node_modules/pdfjs-dist/wasm',
]
